/-
Copyright (c) 2026 LANA Project. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: LANA Project
-/
import Mathlib

/-!
# The Tate analytic quotient `Kˣ / qᶻ`

This file records the first, purely group-theoretic, layer of Tate's
`q`-uniformization of an elliptic curve with split multiplicative reduction.

Fix a complete nonarchimedean field `K` (here modelled by a `NormedField`) and a
*Tate parameter* `q ∈ Kˣ` with `0 < ‖q‖ < 1`.  Multiplication by `q` generates a
cyclic subgroup `qᶻ ≤ Kˣ`, and the analytic torus underlying the Tate curve is the
quotient group `Kˣ / qᶻ`.

We package the datum, show that `q` has infinite (multiplicative) order — so `qᶻ`
is a free abelian group of rank one — and introduce the quotient `Kˣ / qᶻ` as a
commutative group.

The Weierstrass model `E_q`, the group isomorphism `Kˣ / qᶻ ≃ E_q(K)`, and
functoriality under complete field extensions are developed on top of this file.

## Main definitions

* `TateCurvesTheta.TateDatum` : a unit `q` of a normed field with `‖q‖ < 1`.
* `TateDatum.qpowers` : the subgroup `qᶻ ≤ Kˣ`.
* `TateDatum.AnalyticQuotient` : the group `Kˣ / qᶻ`.

## Main results

* `TateDatum.q_zpow_injective` : `n ↦ qⁿ` is injective, i.e. `q` has infinite order.
* `TateDatum.qpowers_infinite` : `qᶻ` is infinite.

## References

* J. Tate, *A review of non-Archimedean elliptic functions*.
* J. Silverman, *Advanced Topics in the Arithmetic of Elliptic Curves*, Chapter V.
-/

namespace TateCurvesTheta

/-- A **Tate datum** over a normed field `K`: a unit `q` whose norm is strictly less
than one.  This is the archetype of the multiplicative parameter of a Tate elliptic
curve with split multiplicative reduction. -/
structure TateDatum (K : Type*) [NormedField K] where
  /-- The Tate parameter, a unit of `K`. -/
  q : Kˣ
  /-- The defining smallness condition `‖q‖ < 1`. -/
  norm_q_lt_one : ‖(q : K)‖ < 1

namespace TateDatum

variable {K : Type*} [NormedField K] (T : TateDatum K)

/-- The norm of the Tate parameter is strictly positive. -/
lemma norm_q_pos : 0 < ‖(T.q : K)‖ :=
  norm_pos_iff.mpr T.q.ne_zero

/-- The norm of the Tate parameter is nonzero. -/
lemma norm_q_ne_zero : ‖(T.q : K)‖ ≠ 0 :=
  T.norm_q_pos.ne'

/-- The Tate parameter is not equal to one, since its norm is `< 1` while `‖1‖ = 1`. -/
lemma q_ne_one : T.q ≠ 1 := by
  intro h
  have : ‖(T.q : K)‖ = 1 := by rw [h]; simp
  exact absurd this (by simpa using T.norm_q_lt_one.ne)

/-- The norm of an integer power of `q` is the corresponding power of `‖q‖`. -/
lemma norm_val_zpow (n : ℤ) : ‖((T.q ^ n : Kˣ) : K)‖ = ‖(T.q : K)‖ ^ n := by
  rw [Units.val_zpow_eq_zpow_val, norm_zpow]

/-- The map `n ↦ qⁿ` from `ℤ` to `Kˣ` is injective: `q` has infinite multiplicative
order.  Distinct integer powers of `q` have distinct norms because `0 < ‖q‖ < 1`. -/
lemma q_zpow_injective : Function.Injective (fun n : ℤ => T.q ^ n) := by
  intro m n h
  have hnorm : ‖(T.q : K)‖ ^ m = ‖(T.q : K)‖ ^ n := by
    have := congrArg (fun u : Kˣ => ‖(u : K)‖) h
    simpa only [norm_val_zpow] using this
  exact zpow_right_injective₀ T.norm_q_pos T.norm_q_lt_one.ne hnorm

/-- The subgroup `qᶻ ≤ Kˣ` generated by the Tate parameter. -/
def qpowers : Subgroup Kˣ := Subgroup.zpowers T.q

@[simp] lemma q_mem_qpowers : T.q ∈ T.qpowers := Subgroup.mem_zpowers T.q

/-- The subgroup `qᶻ` is infinite: it is the image of the injective map `n ↦ qⁿ`. -/
lemma qpowers_infinite : (T.qpowers : Set Kˣ).Infinite := by
  apply Set.infinite_coe_iff.mp
  refine Set.infinite_coe_iff.mpr ?_
  have : Set.range (fun n : ℤ => T.q ^ n) ⊆ (T.qpowers : Set Kˣ) := by
    rintro _ ⟨n, rfl⟩
    exact Subgroup.zpow_mem _ (Subgroup.mem_zpowers _) n
  exact (Set.infinite_range_of_injective T.q_zpow_injective).mono this

/-- The **Tate analytic quotient** `Kˣ / qᶻ`.  This commutative group is the group of
`K`-points of the Tate curve `E_q`. -/
abbrev AnalyticQuotient := Kˣ ⧸ T.qpowers

/-- The natural projection `Kˣ → Kˣ / qᶻ`. -/
abbrev toAnalyticQuotient : Kˣ →* T.AnalyticQuotient := QuotientGroup.mk' T.qpowers

/-- The Tate parameter maps to the identity in the analytic quotient. -/
@[simp] lemma toAnalyticQuotient_q : T.toAnalyticQuotient T.q = 1 := by
  rw [QuotientGroup.mk'_apply, QuotientGroup.eq_one_iff]
  exact T.q_mem_qpowers

end TateDatum

end TateCurvesTheta
