/-
Copyright (c) 2026 The tate-curves-theta contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The tate-curves-theta contributors
-/
import Mathlib.Analysis.Normed.Field.Basic
import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Analysis.SpecificLimits.Normed

/-!
# The Tate `q`-parameter

This file introduces the *Tate parameter* attached to a Tate elliptic curve: an element
`q` of the base field with `0 < ‖q‖ < 1`, together with its normalized additive order.

Over a complete nonarchimedean field `K`, a Tate curve is uniformized by the analytic
quotient `K̄ˣ / qᶻ`, and the multiplicative group generated by `q` is discrete precisely
because `0 < ‖q‖ < 1`. This module isolates the purely metric core of that datum, which
needs neither the nonarchimedean (ultrametric) hypothesis nor completeness: those enter in
the later files that build the `qᶻ`-action, the analytic quotient and the uniformization.

## Main definitions

* `TateCurvesTheta.TateParameter K`: an element `q : Kˣ` with `‖q‖ < 1`.
* `TateCurvesTheta.TateParameter.ord`: the normalized additive order `-Real.log ‖q‖`, a
  strictly positive real. This is the local-height/order convention of a Tate parameter
  (IUT I, Definition 3.1(c)); the integer/discrete normalization coming from a normalized
  valuation is deferred to the shared valuation infrastructure and refines this real order.

## Main results

* `TateParameter.ord_pos`: `0 < ord q`.
* `TateParameter.pow_ne_one`: `q` is not a root of unity (`qⁿ ≠ 1` for `n > 0`).
* `TateParameter.tendsto_pow_atTop_zero`: `qⁿ → 0`, so the positive powers of `q`
  accumulate only at `0`.

## References

* J. Tate, *A review of non-Archimedean elliptic functions*.
* J. H. Silverman, *Advanced Topics in the Arithmetic of Elliptic Curves*, Chapter V.
* S. Mochizuki, *Inter-universal Teichmüller Theory I*, Definition 3.1(c).
-/

open Filter Topology

namespace TateCurvesTheta

variable (K : Type*) [NormedField K]

/-- A **Tate parameter** over a normed field `K`: a unit `q` with `‖q‖ < 1`.

The positivity `0 < ‖q‖` is automatic (`q` is a unit, hence nonzero), so the only genuine
field is the strict upper bound `‖q‖ < 1`. Over a complete nonarchimedean field this is the
datum from which the Tate curve `E_q` and its `q`-uniformization are built. -/
structure TateParameter where
  /-- The underlying unit of the base field. -/
  q : Kˣ
  /-- The Tate parameter has absolute value strictly less than one. -/
  norm_lt_one : ‖(q : K)‖ < 1

namespace TateParameter

variable {K}
variable (t : TateParameter K)

/-- The norm of a Tate parameter is strictly positive. -/
lemma norm_q_pos : 0 < ‖(t.q : K)‖ :=
  norm_pos_iff.mpr t.q.ne_zero

/-- The **normalized additive order** of a Tate parameter, `-log ‖q‖`.

This is the real-valued local order/height of `q`; the discrete (integer- or rational-valued)
normalization supplied by a normalized additive valuation refines it. -/
noncomputable def ord : ℝ := -Real.log ‖(t.q : K)‖

/-- The normalized additive order of a Tate parameter is strictly positive. -/
lemma ord_pos : 0 < t.ord := by
  have hlog : Real.log ‖(t.q : K)‖ < 0 := Real.log_neg t.norm_q_pos t.norm_lt_one
  simpa [ord] using neg_pos.mpr hlog

/-- A Tate parameter is not a root of unity: no positive power of `q` equals `1`. -/
lemma pow_ne_one {n : ℕ} (hn : 0 < n) : (t.q : K) ^ n ≠ 1 := by
  intro h
  have hnorm : ‖(t.q : K)‖ ^ n = 1 := by rw [← norm_pow, h, norm_one]
  have hlt : ‖(t.q : K)‖ ^ n < 1 :=
    pow_lt_one₀ (norm_nonneg _) t.norm_lt_one hn.ne'
  rw [hnorm] at hlt
  exact lt_irrefl (1 : ℝ) hlt

/-- The positive powers of a Tate parameter tend to `0`: the subgroup `qᶻ` accumulates only
at `0`. -/
lemma tendsto_pow_atTop_zero :
    Tendsto (fun n : ℕ => (t.q : K) ^ n) atTop (𝓝 0) :=
  tendsto_pow_atTop_nhds_zero_of_norm_lt_one t.norm_lt_one

end TateParameter

end TateCurvesTheta
