/-
Copyright (c) 2026 The tate-curves-theta contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The tate-curves-theta contributors
-/
import TateCurvesTheta.QParameter.BaseChange
import TateCurvesTheta.QParameter.PrimeToOrder

/-!
# The discrete normalized order of the Tate parameter

When the norm of `K` is *discrete* — its value group on `Kˣ` is generated by the norm of a
**uniformizer** `π` (`IsUniformizer`) — the real-valued order `ord q = -log ‖q‖` of a Tate
parameter refines to a canonical positive integer: the unique `n` with `‖q‖ = ‖π‖ⁿ`. This
is the **normalized additive order** of the `q`-parameter in the convention of IUT I,
Definition 3.1(c): the additive valuation is normalized so that `ord π = 1`, and then
`ord q = orderZ ∈ ℤ_{>0}` (`ord_eq_orderZ_mul`). It supplies the canonical value for the
`orderNat` seam of `OrderedTateParameter` (`toOrdered`), on which the Θ-data coprimality
predicate `PrimeToOrder` operates.

**Local vs. global.** The datum formalized here is the *local* `q`-parameter of a Tate
curve over one complete nonarchimedean field, and its normalized local order/height. The
*global* `q`-pilot object of IUT (a collection of local `q`-parameters at the bad places,
entering the log-volume computations) is a different, later construction layered on top
of these local data; only the local convention is fixed in this repository.

**Ramification.** Under an isometric extension `L/K` the real order is unchanged
(`ord_baseChange`); the integer order is unchanged exactly when `π` remains a uniformizer
of `L` (`orderZ_baseChange`, e.g. unramified extensions). For ramified `L/K` a uniformizer
`π_L` satisfies `‖π_L‖^e = ‖π‖` and the integer order scales by `e(L/K)`; that bookkeeping
belongs to the shared normalized-valuation infrastructure (project-3 issue #4), and the
interface here is stated so that it can be plugged in without changing any statement.

## Main definitions

* `TateCurvesTheta.IsUniformizer π`: `π ≠ 0`, `‖π‖ < 1`, and `‖π‖` generates the value
  group of `Kˣ`.
* `TateCurvesTheta.TateParameter.orderZ`: the discrete normalized order `n` with
  `‖q‖ = ‖π‖ⁿ`.
* `TateCurvesTheta.TateParameter.toOrdered`: the canonical `OrderedTateParameter`.
* `TateCurvesTheta.TateParameter.localHeight`: the normalized local height of the
  `q`-parameter (IUT I, Definition 3.1(c) convention).

## Main results

* `TateParameter.orderZ_pos`, `TateParameter.norm_q_eq_zpow`,
  `TateParameter.orderZ_eq_of_norm` (uniqueness).
* `TateParameter.ord_eq_orderZ_mul`: `ord q = orderZ · ord π` — the normalization
  `ord π = 1` makes the order of `q` the integer `orderZ`.
* `TateParameter.orderZ_baseChange`: invariance when `π` stays a uniformizer.

## References

* S. Mochizuki, *Inter-universal Teichmüller Theory I*, Definition 3.1(c).
* J. H. Silverman, *Advanced Topics in the Arithmetic of Elliptic Curves*, Ch. II, V.
-/

namespace TateCurvesTheta

variable {K : Type*} [NormedField K]

/-- A **uniformizer** for the norm of `K`: a nonzero element of norm `< 1` whose norm
generates the value group `‖Kˣ‖`. This is the discreteness datum under which the
real-valued order of a Tate parameter refines to a canonical integer. -/
structure IsUniformizer (π : K) : Prop where
  /-- A uniformizer is nonzero. -/
  ne_zero : π ≠ 0
  /-- A uniformizer is topologically nilpotent: `‖π‖ < 1`. -/
  norm_lt_one : ‖π‖ < 1
  /-- The norm of every unit is an integer power of `‖π‖`. -/
  generates : ∀ x : Kˣ, ∃ n : ℤ, ‖(x : K)‖ = ‖π‖ ^ n

namespace IsUniformizer

variable {π : K}

lemma norm_pos (hπ : IsUniformizer π) : 0 < ‖π‖ := norm_pos_iff.mpr hπ.ne_zero

lemma log_norm_neg (hπ : IsUniformizer π) : Real.log ‖π‖ < 0 :=
  Real.log_neg hπ.norm_pos hπ.norm_lt_one

lemma log_norm_ne_zero (hπ : IsUniformizer π) : Real.log ‖π‖ ≠ 0 := ne_of_lt hπ.log_norm_neg

/-- The exponent of a norm value with respect to a uniformizer is unique. -/
lemma zpow_right_injective (hπ : IsUniformizer π) :
    Function.Injective fun n : ℤ => ‖π‖ ^ n := by
  intro m n h
  have hlog := congrArg Real.log h
  simp only [Real.log_zpow] at hlog
  exact_mod_cast mul_right_cancel₀ hπ.log_norm_ne_zero hlog

end IsUniformizer

namespace TateParameter

variable (t : TateParameter K) {π : K}

lemma exists_norm_q_eq_zpow (hπ : IsUniformizer π) : ∃ n : ℤ, ‖(t.q : K)‖ = ‖π‖ ^ n :=
  hπ.generates t.q

/-- **The discrete normalized order** of a Tate parameter with respect to a uniformizer
`π`: the unique integer `n` with `‖q‖ = ‖π‖ⁿ`. In the convention of IUT I,
Definition 3.1(c) — additive order normalized so that `ord π = 1` — this *is* the order
of the `q`-parameter (`ord_eq_orderZ_mul`). -/
noncomputable def orderZ (hπ : IsUniformizer π) : ℤ :=
  Classical.choose (t.exists_norm_q_eq_zpow hπ)

lemma norm_q_eq_zpow (hπ : IsUniformizer π) : ‖(t.q : K)‖ = ‖π‖ ^ t.orderZ hπ :=
  Classical.choose_spec (t.exists_norm_q_eq_zpow hπ)

/-- Uniqueness of the discrete order: any exponent representing `‖q‖` equals `orderZ`. -/
lemma orderZ_eq_of_norm (hπ : IsUniformizer π) {n : ℤ} (h : ‖(t.q : K)‖ = ‖π‖ ^ n) :
    t.orderZ hπ = n :=
  hπ.zpow_right_injective ((t.norm_q_eq_zpow hπ).symm.trans h)

/-- The discrete normalized order of a Tate parameter is strictly positive. -/
theorem orderZ_pos (hπ : IsUniformizer π) : 0 < t.orderZ hπ := by
  have hq : Real.log ‖(t.q : K)‖ < 0 := Real.log_neg t.norm_q_pos t.norm_lt_one
  have heq : Real.log ‖(t.q : K)‖ = (t.orderZ hπ : ℝ) * Real.log ‖π‖ := by
    rw [t.norm_q_eq_zpow hπ, Real.log_zpow]
  by_contra hcon
  rw [not_lt] at hcon
  have hcast : (t.orderZ hπ : ℝ) ≤ 0 := by exact_mod_cast hcon
  have hnonneg : (0 : ℝ) ≤ (t.orderZ hπ : ℝ) * Real.log ‖π‖ := by
    nlinarith [hπ.log_norm_neg.le]
  rw [heq] at hq
  linarith

/-- **The IUT normalization**: `ord q = orderZ · ord π`. With the additive order
normalized so that `ord π = 1`, the order of the `q`-parameter is the positive integer
`orderZ` — the convention of IUT I, Definition 3.1(c). -/
theorem ord_eq_orderZ_mul (hπ : IsUniformizer π) :
    t.ord = (t.orderZ hπ : ℝ) * -Real.log ‖π‖ := by
  rw [ord, t.norm_q_eq_zpow hπ, Real.log_zpow]
  ring

/-- **The normalized local height** of the `q`-parameter: its discrete order, as a real
number (the local-height convention of IUT I, Definition 3.1(c), in units `ord π = 1`). -/
noncomputable def localHeight (hπ : IsUniformizer π) : ℝ := (t.orderZ hπ : ℝ)

lemma localHeight_pos (hπ : IsUniformizer π) : 0 < t.localHeight hπ := by
  have := t.orderZ_pos hπ
  rw [localHeight]
  exact_mod_cast this

/-- The local height is the real order measured in units of `ord π`. -/
lemma localHeight_eq_ord_div (hπ : IsUniformizer π) :
    t.localHeight hπ = t.ord / -Real.log ‖π‖ := by
  rw [localHeight, t.ord_eq_orderZ_mul hπ,
    mul_div_cancel_right₀ _ (neg_ne_zero.mpr hπ.log_norm_ne_zero)]

/-- **The canonical `OrderedTateParameter`**: the discrete normalized order supplies the
canonical value for the `orderNat` seam of `PrimeToOrder.lean`. -/
noncomputable def toOrdered (hπ : IsUniformizer π) : OrderedTateParameter K :=
  { t with
    orderNat := (t.orderZ hπ).toNat
    orderNat_pos := by
      have := t.orderZ_pos hπ
      omega }

@[simp] lemma toOrdered_orderNat (hπ : IsUniformizer π) :
    (t.toOrdered hπ).orderNat = (t.orderZ hπ).toNat := rfl

@[simp] lemma toOrdered_toTateParameter (hπ : IsUniformizer π) :
    (t.toOrdered hπ).toTateParameter = t := rfl

/-- The defining property of the canonical integer order, in `ℕ`-power form. -/
lemma norm_q_eq_pow_orderNat (hπ : IsUniformizer π) :
    ‖(t.q : K)‖ = ‖π‖ ^ (t.toOrdered hπ).orderNat := by
  have hpos := t.orderZ_pos hπ
  rw [toOrdered_orderNat, ← zpow_natCast, Int.toNat_of_nonneg hpos.le]
  exact t.norm_q_eq_zpow hπ

/-- The Θ-data condition for the canonical order: `ℓ` is prime to the order of `q`. -/
lemma toOrdered_primeToOrder_iff (hπ : IsUniformizer π) (ℓ : ℕ) :
    (t.toOrdered hπ).PrimeToOrder ℓ ↔ Nat.Coprime ℓ (t.orderZ hπ).toNat :=
  Iff.rfl

section BaseChange

variable (L : Type*) [NormedField L] [NormedAlgebra K L]

/-- **Base-change invariance of the discrete order** when `π` remains a uniformizer of
`L` (e.g. an unramified extension): the integer order of the base-changed parameter with
respect to `algebraMap K L π` is unchanged. In a ramified extension the order instead
scales by the ramification index; that bookkeeping is deferred to the shared valuation
infrastructure (see the module docstring). -/
lemma orderZ_baseChange (hπ : IsUniformizer π) (hπL : IsUniformizer (algebraMap K L π)) :
    (t.baseChange L).orderZ hπL = t.orderZ hπ := by
  apply (t.baseChange L).orderZ_eq_of_norm hπL
  rw [norm_baseChange, norm_algebraMap', t.norm_q_eq_zpow hπ]

end BaseChange

end TateParameter

end TateCurvesTheta
