name = "tate-curves-theta"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["TateCurvesTheta"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.0"

[[require]]
name = "formal-schemes"
git = "https://github.com/lana-agents/formal-schemes"
rev = "51aa935079537bf4dc580751a6e70727fb23ca93"

[[lean_lib]]
name = "TateCurvesTheta"
