/-
Copyright (c) 2026 The tate-curves-theta contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The tate-curves-theta contributors
-/
import Mathlib.LinearAlgebra.FiniteDimensional.Basic
import TateCurvesTheta.Theta.Durfee
import TateCurvesTheta.Theta.LaurentUnitSphere
import TateCurvesTheta.Theta.Periodicity
import TateCurvesTheta.Theta.ThetaProdGlobalLaurent

/-!
# Weight spaces of theta functions for the Tate parameter

For a Tate parameter `q` over a complete nonarchimedean field `K`, a **weight-`k` theta
family with multiplier `A ∈ Kˣ`** is a globally summable Laurent coefficient family
`c : ℤ → K` satisfying the recursion
```
A · c (n + k) = qⁿ · c n,
```
equivalently (at the level of values) `F(q·u) = A·u⁻ᵏ·F(u)` for `F(u) = ∑' n, cₙ uⁿ` — the
classical functional equation of a theta function of weight `k` for the lattice `qᶻ`.

The recursion pins the whole family down from the `k` initial coefficients `c 0, …, c (k-1)`,
and conversely every choice of initial coefficients extends (with theta-type coefficient
decay, hence global summability). Packaging the families as a `Submodule K (ℤ → K)` this
gives a `K`-linear equivalence `weightSpace k A ≃ₗ Fin k → K`: **the space of weight-`k`
theta functions is `k`-dimensional**. This finite-dimensionality is the engine that replaces
divisor theory in the analytic development of the Tate parametrization: convolution
multiplies weight families (`IsWeightFamily.conv`), evaluation at a point is a linear
functional, and multiplication by a fixed theta block `n ↦ q^{thetaExp n} eⁿ` (the family of
`u ↦ θ(e·u)`) is an injective linear map whose image is exactly the subspace of families
vanishing on the block's zero class — nonarchimedean Abel theory in finite dimensions.

## Main definitions

* `TateCurvesTheta.TateParameter.IsWeightFamily`: the weight-`k` recursion + global
  summability predicate.
* `TateCurvesTheta.TateParameter.weightSpace`: the families as a submodule of `ℤ → K`.
* `TateCurvesTheta.TateParameter.weightExtend`: the family generated by `k` initial
  coefficients.
* `TateCurvesTheta.TateParameter.weightEquiv`: `weightSpace t k A ≃ₗ[K] (Fin k → K)`.
* `TateCurvesTheta.TateParameter.thetaBlock`: the weight-one family of `u ↦ θ(e·u)`.

## Main results

* `TateParameter.IsWeightFamily.tsum_q_smul`: the value-level functional equation.
* `TateParameter.IsWeightFamily.ext_initial`: a weight family is determined by its `k`
  initial coefficients.
* `TateParameter.IsWeightFamily.conv`: convolution adds weights and multiplies multipliers.
* `TateParameter.finrank_weightSpace`: `finrank (weightSpace t k A) = k`.

## References

* J. Tate, *A review of non-Archimedean elliptic functions*.
* D. Mumford, *Tata Lectures on Theta* I.
* P. Roquette, *Analytic theory of elliptic functions over local fields*.
-/

open Filter Topology

noncomputable section

namespace TateCurvesTheta

namespace TateParameter

variable {K : Type*} [NormedField K] [CompleteSpace K] [IsUltrametricDist K]
variable (t : TateParameter K)

/-! ### The weight-`k` recursion -/

/-- A **weight-`k` theta family with multiplier `A`**: a globally summable Laurent
coefficient family satisfying `A·c(n+k) = qⁿ·cₙ`. At the level of values this is the theta
functional equation `F(qu) = A·u⁻ᵏ·F(u)`. -/
structure IsWeightFamily (k : ℕ) (A : Kˣ) (c : ℤ → K) : Prop where
  summable : ∀ u : Kˣ, Summable fun n : ℤ => c n * (u : K) ^ n
  step : ∀ n : ℤ, (A : K) * c (n + k) = (t.q : K) ^ n * c n

namespace IsWeightFamily

variable {t}
variable {k l : ℕ} {A B : Kˣ} {c d : ℤ → K}

omit [CompleteSpace K] [IsUltrametricDist K] in
lemma zero : t.IsWeightFamily k A (fun _ => 0) :=
  ⟨fun u => by simp, fun n => by simp⟩

omit [CompleteSpace K] [IsUltrametricDist K] in
lemma add (hc : t.IsWeightFamily k A c) (hd : t.IsWeightFamily k A d) :
    t.IsWeightFamily k A (c + d) := by
  refine ⟨fun u => ?_, fun n => ?_⟩
  · refine ((hc.summable u).add (hd.summable u)).congr fun n => ?_
    simp [add_mul]
  · have h1 := hc.step n
    have h2 := hd.step n
    simp only [Pi.add_apply]
    linear_combination h1 + h2

omit [CompleteSpace K] [IsUltrametricDist K] in
lemma smul (a : K) (hc : t.IsWeightFamily k A c) : t.IsWeightFamily k A (a • c) := by
  refine ⟨fun u => ?_, fun n => ?_⟩
  · refine ((hc.summable u).mul_left a).congr fun n => ?_
    simp [mul_assoc]
  · have h1 := hc.step n
    simp only [Pi.smul_apply, smul_eq_mul]
    linear_combination a * h1

/-- **The value-level functional equation**: `∑ₙ cₙ (qu)ⁿ = A·u⁻ᵏ·∑ₙ cₙ uⁿ`. -/
theorem tsum_q_smul (hc : t.IsWeightFamily k A c) (u : Kˣ) :
    (∑' n : ℤ, c n * ((t.q : K) * (u : K)) ^ n)
      = (A : K) * (u : K) ^ (-(k : ℤ)) * ∑' n : ℤ, c n * (u : K) ^ n := by
  have h1 : (∑' n : ℤ, c n * ((t.q : K) * (u : K)) ^ n)
      = ∑' n : ℤ, (A : K) * c (n + k) * (u : K) ^ n := by
    refine tsum_congr fun n => ?_
    rw [mul_zpow]
    calc c n * ((t.q : K) ^ n * (u : K) ^ n)
        = ((t.q : K) ^ n * c n) * (u : K) ^ n := by ring
      _ = ((A : K) * c (n + k)) * (u : K) ^ n := by rw [hc.step n]
  rw [h1]
  have hshift : Summable fun n : ℤ => c (n + k) * (u : K) ^ (n + k) :=
    (hc.summable u).comp_injective (add_left_injective (k : ℤ))
  have h2 : (∑' n : ℤ, (A : K) * c (n + k) * (u : K) ^ n)
      = (A : K) * (u : K) ^ (-(k : ℤ)) * ∑' n : ℤ, c (n + k) * (u : K) ^ (n + k) := by
    rw [← tsum_mul_left]
    refine tsum_congr fun n => ?_
    rw [zpow_add₀ (Units.ne_zero u), zpow_neg]
    field_simp
  rw [h2]
  congr 1
  rw [← (Equiv.addRight (k : ℤ)).tsum_eq fun n => c n * (u : K) ^ n]
  exact tsum_congr fun n => rfl

/-- **The converse**: a globally summable family whose series satisfies the value-level
functional equation is a weight family — by coefficient uniqueness. -/
theorem of_tsum_q_smul (hsum : ∀ u : Kˣ, Summable fun n : ℤ => c n * (u : K) ^ n)
    (h : ∀ u : Kˣ, (∑' n : ℤ, c n * ((t.q : K) * (u : K)) ^ n)
      = (A : K) * (u : K) ^ (-(k : ℤ)) * ∑' n : ℤ, c n * (u : K) ^ n) :
    t.IsWeightFamily k A c := by
  refine ⟨hsum, fun n => ?_⟩
  have huniq := t.laurentCoeffUnique
  have hsumA : ∀ u : Kˣ, Summable fun n : ℤ => ((t.q : K) ^ n * c n) * (u : K) ^ n := by
    intro u
    refine (hsum (t.q * u)).congr fun n => ?_
    rw [Units.val_mul, mul_zpow]
    ring
  have hsumB : ∀ u : Kˣ, Summable fun n : ℤ => ((A : K) * c (n + k)) * (u : K) ^ n := by
    intro u
    have hshift : Summable fun n : ℤ => c (n + k) * (u : K) ^ n := by
      have h1 : Summable fun n : ℤ => c (n + k) * (u : K) ^ (n + k) :=
        (hsum u).comp_injective (add_left_injective (k : ℤ))
      have h2 := h1.mul_right ((u : K) ^ (-(k : ℤ)))
      refine h2.congr fun n => ?_
      rw [mul_assoc, ← zpow_add₀ (Units.ne_zero u)]
      congr 2
      omega
    refine (hshift.mul_left (A : K)).congr fun n => ?_
    ring
  have key : (fun n : ℤ => (t.q : K) ^ n * c n) = fun n : ℤ => (A : K) * c (n + k) := by
    refine huniq _ _ hsumA hsumB fun u => ?_
    have hL : (∑' n : ℤ, ((t.q : K) ^ n * c n) * (u : K) ^ n)
        = ∑' n : ℤ, c n * ((t.q : K) * (u : K)) ^ n := by
      refine tsum_congr fun n => ?_
      rw [mul_zpow]
      ring
    have hR : (∑' n : ℤ, ((A : K) * c (n + k)) * (u : K) ^ n)
        = (A : K) * (u : K) ^ (-(k : ℤ)) * ∑' n : ℤ, c n * (u : K) ^ n := by
      have h2 : (∑' n : ℤ, c (n + k) * (u : K) ^ (n + k))
          = ∑' n : ℤ, c n * (u : K) ^ n := by
        rw [← (Equiv.addRight (k : ℤ)).tsum_eq fun n => c n * (u : K) ^ n]
        exact tsum_congr fun n => rfl
      rw [← h2, ← tsum_mul_left]
      refine tsum_congr fun n => ?_
      rw [zpow_add₀ (Units.ne_zero u), zpow_neg]
      field_simp
    rw [hL, hR, h u]
  have hkey := congrFun key n
  linear_combination -hkey

omit [CompleteSpace K] [IsUltrametricDist K] in
/-- **Determination**: a weight-`k` family is pinned down by its `k` initial coefficients
`c 0, …, c (k-1)`. -/
theorem ext_initial (hk : 0 < k) (hc : t.IsWeightFamily k A c) (hd : t.IsWeightFamily k A d)
    (h : ∀ i : ℕ, i < k → c i = d i) : c = d := by
  have hq0 : (t.q : K) ≠ 0 := t.q.ne_zero
  have hA0 : (A : K) ≠ 0 := Units.ne_zero A
  -- the difference satisfies the recursion and vanishes on the initial window
  have key : ∀ m : ℤ, ∀ i : ℕ, i < k → c (i + k * m) = d (i + k * m) := by
    intro m
    induction m using Int.induction_on with
    | zero => intro i hi; simpa using h i hi
    | succ m ih =>
      intro i hi
      have hstep_c := hc.step (i + k * m)
      have hstep_d := hd.step (i + k * m)
      have hprev := ih i hi
      have harg : (i : ℤ) + k * m + k = i + k * (m + 1) := by ring
      rw [harg] at hstep_c hstep_d
      have : (A : K) * c (i + k * (m + 1)) = (A : K) * d (i + k * (m + 1)) := by
        rw [hstep_c, hstep_d, hprev]
      exact mul_left_cancel₀ hA0 this
    | pred m ih =>
      intro i hi
      have hstep_c := hc.step (i + k * (-m - 1))
      have hstep_d := hd.step (i + k * (-m - 1))
      have hnext := ih i hi
      have harg : (i : ℤ) + k * (-m - 1) + k = i + k * (-(m : ℤ)) := by ring
      rw [harg] at hstep_c hstep_d
      have hpow : ((t.q : K) ^ ((i : ℤ) + k * (-m - 1))) ≠ 0 := zpow_ne_zero _ hq0
      have : (t.q : K) ^ ((i : ℤ) + k * (-m - 1)) * c (i + k * (-m - 1))
          = (t.q : K) ^ ((i : ℤ) + k * (-m - 1)) * d (i + k * (-m - 1)) := by
        rw [← hstep_c, ← hstep_d, hnext]
      exact mul_left_cancel₀ hpow this
  funext n
  have hik : (0 : ℤ) < k := by exact_mod_cast hk
  have hmod : n % k + k * (n / k) = n := by
    rw [Int.emod_def]
    ring
  have hi0 : 0 ≤ n % k := Int.emod_nonneg n (by omega)
  have hik' : n % k < k := Int.emod_lt_of_pos n hik
  have := key (n / k) (n % k).toNat (by omega)
  rw [Int.toNat_of_nonneg hi0] at this
  rwa [hmod] at this

/-- **Convolution of weight families**: weights add and multipliers multiply. This is the
coefficient-level product of theta functions. -/
theorem conv (hc : t.IsWeightFamily k A c) (hd : t.IsWeightFamily l B d) :
    t.IsWeightFamily (k + l) (A * B) fun n => ∑' m : ℤ, c (n - m) * d m := by
  have hq0 : (t.q : K) ≠ 0 := t.q.ne_zero
  constructor
  · intro u
    exact (hasSum_laurentConvolution u (hc.summable u).hasSum (hd.summable u).hasSum).summable
  · intro n
    calc ((A * B : Kˣ) : K) * ∑' m : ℤ, c (n + (k + l : ℕ) - m) * d m
        = ∑' m : ℤ, ((A : K) * (B : K)) * (c (n + (k + l : ℕ) - m) * d m) := by
          rw [tsum_mul_left, Units.val_mul]
      _ = ∑' m : ℤ, ((A : K) * (B : K)) * (c (n + (k + l : ℕ) - (m + l)) * d (m + l)) := by
          rw [← (Equiv.addRight (l : ℤ)).tsum_eq fun m =>
            ((A : K) * (B : K)) * (c (n + (k + l : ℕ) - m) * d m)]
          exact tsum_congr fun m => rfl
      _ = ∑' m : ℤ, (t.q : K) ^ n * (c (n - m) * d m) := by
          refine tsum_congr fun m => ?_
          have h1 : n + ((k : ℤ) + l) - (m + l) = (n - m) + k := by ring
          rw [Nat.cast_add, h1]
          calc ((A : K) * (B : K)) * (c ((n - m) + k) * d (m + l))
              = ((A : K) * c ((n - m) + k)) * ((B : K) * d (m + l)) := by ring
            _ = ((t.q : K) ^ (n - m) * c (n - m)) * ((t.q : K) ^ m * d m) := by
                rw [hc.step (n - m), hd.step m]
            _ = (t.q : K) ^ n * (c (n - m) * d m) := by
                rw [show (t.q : K) ^ (n - m) * c (n - m) * ((t.q : K) ^ m * d m)
                    = ((t.q : K) ^ (n - m) * (t.q : K) ^ m) * (c (n - m) * d m) by ring,
                  ← zpow_add₀ hq0]
                congr 2
                omega
      _ = (t.q : K) ^ n * ∑' m : ℤ, c (n - m) * d m := by rw [tsum_mul_left]

/-- The series of a convolution evaluates to the product of the two series. -/
theorem conv_hasSum (hc : t.IsWeightFamily k A c) (hd : t.IsWeightFamily l B d) (u : Kˣ) :
    HasSum (fun n : ℤ => (∑' m : ℤ, c (n - m) * d m) * (u : K) ^ n)
      ((∑' n : ℤ, c n * (u : K) ^ n) * ∑' n : ℤ, d n * (u : K) ^ n) :=
  hasSum_laurentConvolution u (hc.summable u).hasSum (hd.summable u).hasSum

end IsWeightFamily

/-! ### Extension of initial coefficients and the dimension count -/

section Extend

variable {t}
variable {k : ℕ} {A : Kˣ}

/-- The **weight extension**: the family generated from `k` initial coefficients by the
weight recursion, in closed form `c (i + k·m) = A⁻ᵐ · q^{m·i + k·e(m-1)} · v i`. -/
def weightExtend (hk : 0 < k) (A : Kˣ) (v : Fin k → K) : ℤ → K := fun n =>
  ((A⁻¹ : Kˣ) : K) ^ (n / k) * (t.q : K) ^ ((n / k) * (n % k) + k * thetaExp (n / k - 1))
    * v ⟨(n % k).toNat, by
        have h1 : 0 ≤ n % k := Int.emod_nonneg n (by positivity)
        have h2 : n % k < k := Int.emod_lt_of_pos n (by exact_mod_cast hk)
        omega⟩

omit [CompleteSpace K] [IsUltrametricDist K] in
private lemma emod_fiber (hk : 0 < k) (i : ℕ) (hi : i < k) (m : ℤ) :
    ((i : ℤ) + k * m) % k = i ∧ ((i : ℤ) + k * m) / k = m := by
  constructor
  · rw [Int.add_mul_emod_self_left]
    exact Int.emod_eq_of_lt (by positivity) (by exact_mod_cast hi)
  · rw [Int.add_mul_ediv_left _ _ (by positivity : (k : ℤ) ≠ 0),
      Int.ediv_eq_zero_of_lt (by positivity) (by exact_mod_cast hi), zero_add]

omit [CompleteSpace K] [IsUltrametricDist K] in
private lemma weightExtend_fiber (hk : 0 < k) (v : Fin k → K) (i : ℕ) (hi : i < k) (m : ℤ) :
    weightExtend (t := t) hk A v ((i : ℤ) + k * m)
      = ((A⁻¹ : Kˣ) : K) ^ m * (t.q : K) ^ (m * i + k * thetaExp (m - 1)) * v ⟨i, hi⟩ := by
  obtain ⟨h1, h2⟩ := emod_fiber hk i hi m
  rw [weightExtend]
  congr 1
  · rw [h1, h2]
  · congr 1
    simp [h1]

omit [CompleteSpace K] [IsUltrametricDist K] in
/-- The extension restricts to the initial coefficients. -/
lemma weightExtend_initial (hk : 0 < k) (v : Fin k → K) (i : ℕ) (hi : i < k) :
    weightExtend (t := t) hk A v i = v ⟨i, hi⟩ := by
  have h := weightExtend_fiber (t := t) (A := A) hk v i hi 0
  have hth : thetaExp (0 - 1) = 0 := by norm_num [thetaExp]
  simp only [mul_zero, add_zero, zero_mul, zpow_zero, one_mul, hth] at h
  simpa using h

omit [CompleteSpace K] [IsUltrametricDist K] in
/-- The extension satisfies the weight recursion. -/
lemma weightExtend_step (hk : 0 < k) (v : Fin k → K) (n : ℤ) :
    (A : K) * weightExtend (t := t) hk A v (n + k)
      = (t.q : K) ^ n * weightExtend (t := t) hk A v n := by
  have hq0 : (t.q : K) ≠ 0 := t.q.ne_zero
  have hA0 : (A : K) ≠ 0 := Units.ne_zero A
  set i : ℤ := n % k with hidef
  set m : ℤ := n / k with hmdef
  have h1 : 0 ≤ i := Int.emod_nonneg n (by positivity)
  have h2 : i < k := Int.emod_lt_of_pos n (by exact_mod_cast hk)
  have hn : n = (i.toNat : ℤ) + k * m := by
    rw [Int.toNat_of_nonneg h1, hidef, hmdef, Int.emod_def]
    ring
  have hnk : n + k = (i.toNat : ℤ) + k * (m + 1) := by rw [hn]; ring
  rw [hnk, hn, weightExtend_fiber hk v i.toNat (by omega) (m + 1),
    weightExtend_fiber hk v i.toNat (by omega) m]
  have hAz : ((A⁻¹ : Kˣ) : K) = (A : K)⁻¹ := Units.val_inv_eq_inv_val A
  rw [hAz, zpow_add₀ (inv_ne_zero hA0), zpow_one]
  have hexp : (m + 1) * (i.toNat : ℤ) + k * thetaExp (m + 1 - 1)
      = ((i.toNat : ℤ) + k * m) + (m * i.toNat + k * thetaExp (m - 1)) := by
    have hth : thetaExp m = thetaExp (m - 1) + m := by
      have h1 := two_mul_thetaExp m
      have h2 := two_mul_thetaExp (m - 1)
      have h3 : m * (m + 1) = (m - 1) * m + 2 * m := by ring
      linarith
    have : (m + 1 - 1) = m := by ring
    rw [this, hth]
    ring
  rw [hexp, zpow_add₀ hq0]
  field_simp

/-- Summability workhorse: theta-type families `m ↦ q^{j·e(m-1)} · Wᵐ` are summable for
every unit `W` and positive scale `j`. -/
private lemma summable_pow_thetaExp_mul (t : TateParameter K) (j : ℕ) (hj : 0 < j) (W : Kˣ) :
    Summable fun m : ℤ => (t.q : K) ^ ((j : ℤ) * thetaExp (m - 1)) * (W : K) ^ m := by
  apply NonarchimedeanAddGroup.summable_of_tendsto_cofinite_zero
  apply tendsto_zero_iff_norm_tendsto_zero.mpr
  have ha : 0 < ‖(t.q : K)‖ := t.norm_q_pos
  have hb : 0 < ‖(W : K)‖ := norm_pos_iff.mpr W.ne_zero
  have hnorm : (fun m : ℤ => ‖(t.q : K) ^ ((j : ℤ) * thetaExp (m - 1)) * (W : K) ^ m‖)
      = fun m : ℤ => Real.exp (Real.log ‖(t.q : K)‖ * (((j : ℤ) * thetaExp (m - 1) : ℤ) : ℝ)
          + Real.log ‖(W : K)‖ * (m : ℝ)) := by
    funext m
    rw [norm_mul, norm_zpow, norm_zpow,
      ← Real.rpow_intCast ‖(t.q : K)‖ _, ← Real.rpow_intCast ‖(W : K)‖ m,
      Real.rpow_def_of_pos ha, Real.rpow_def_of_pos hb, ← Real.exp_add]
  rw [hnorm]
  refine Real.tendsto_exp_atBot.comp ?_
  have hLa2 : (j : ℝ) * Real.log ‖(t.q : K)‖ / 2 < 0 := by
    have hlog := Real.log_neg ha t.norm_lt_one
    have hj' : (0 : ℝ) < j := by exact_mod_cast hj
    nlinarith
  have hfac : (fun m : ℤ => Real.log ‖(t.q : K)‖ * (((j : ℤ) * thetaExp (m - 1) : ℤ) : ℝ)
      + Real.log ‖(W : K)‖ * (m : ℝ))
      = fun m : ℤ => (m : ℝ) * ((Real.log ‖(W : K)‖ - (j : ℝ) * Real.log ‖(t.q : K)‖ / 2)
          + (j : ℝ) * Real.log ‖(t.q : K)‖ / 2 * (m : ℝ)) := by
    funext m
    push_cast [thetaExp_cast]
    ring
  rw [hfac, Int.cofinite_eq, tendsto_sup]
  refine ⟨?_, ?_⟩
  · exact Tendsto.atBot_mul_atTop₀ (tendsto_intCast_atBot_iff.2 tendsto_id)
      (Tendsto.add_atTop tendsto_const_nhds
        (Tendsto.const_mul_atBot_of_neg hLa2 (tendsto_intCast_atBot_iff.2 tendsto_id)))
  · exact Tendsto.atTop_mul_atBot₀ tendsto_intCast_atTop_atTop
      (Tendsto.add_atBot tendsto_const_nhds
        (Tendsto.const_mul_atTop_of_neg hLa2 tendsto_intCast_atTop_atTop))

/-- Each residue-class fiber of the weight extension is summable against any unit. -/
private lemma summable_weightExtend_fiber (hk : 0 < k) (v : Fin k → K) (u : Kˣ)
    (i : ℕ) (hi : i < k) :
    Summable fun m : ℤ =>
      weightExtend (t := t) hk A v ((i : ℤ) + k * m) * (u : K) ^ ((i : ℤ) + k * m) := by
  have hq0 : (t.q : K) ≠ 0 := t.q.ne_zero
  set W : Kˣ := A⁻¹ * t.q ^ i * u ^ k with hW
  have h := (summable_pow_thetaExp_mul t k hk W).mul_left (v ⟨i, hi⟩ * (u : K) ^ (i : ℤ))
  refine h.congr fun m => ?_
  have hWm : ((W : Kˣ) : K) ^ m
      = ((A⁻¹ : Kˣ) : K) ^ m * (t.q : K) ^ ((i : ℤ) * m) * (u : K) ^ ((k : ℤ) * m) := by
    rw [hW]
    push_cast [Units.val_mul, mul_zpow, Units.val_pow_eq_pow_val]
    rw [← zpow_natCast ((t.q : K)) i, ← zpow_natCast ((u : K)) k, zpow_mul, zpow_mul]
  rw [weightExtend_fiber hk v i hi m, hWm,
    zpow_add₀ (Units.ne_zero u) (i : ℤ) ((k : ℤ) * m),
    zpow_add₀ hq0 (m * (i : ℤ)) ((k : ℤ) * thetaExp (m - 1)),
    show m * (i : ℤ) = (i : ℤ) * m from mul_comm _ _]
  ring

/-- The weight extension is globally summable against every unit. -/
private lemma summable_weightExtend (hk : 0 < k) (v : Fin k → K) (u : Kˣ) :
    Summable fun n : ℤ => weightExtend (t := t) hk A v n * (u : K) ^ n := by
  classical
  set f : ℤ → K := fun n => weightExtend (t := t) hk A v n * (u : K) ^ n with hf
  have hsplit : ∀ i ∈ Finset.range k,
      Summable fun n : ℤ => if n % k = i then f n else 0 := by
    intro i hi
    rw [Finset.mem_range] at hi
    have hinj : Function.Injective fun m : ℤ => (i : ℤ) + k * m := by
      intro a b hab
      simp only at hab
      have hk0 : (k : ℤ) ≠ 0 := by positivity
      have h2 : (k : ℤ) * a = (k : ℤ) * b := by linarith
      exact mul_left_cancel₀ hk0 h2
    apply (hinj.summable_iff ?_).mp
    · refine (summable_weightExtend_fiber (t := t) (A := A) hk v u i hi).congr fun m => ?_
      have := (emod_fiber hk i hi m).1
      simp only [Function.comp_apply, hf, this, if_true]
    · intro n hn
      have hne : ¬(n % k = i) := by
        intro hcontra
        refine hn ⟨n / k, ?_⟩
        simp only
        have hdef := Int.emod_def n k
        rw [hcontra] at hdef
        linarith
      simp [hne]
  have hsum := summable_sum hsplit
  refine hsum.congr fun n => ?_
  have h1 : 0 ≤ n % k := Int.emod_nonneg n (by positivity)
  have h2 : n % k < k := Int.emod_lt_of_pos n (by exact_mod_cast hk)
  have hmem : (n % k).toNat ∈ Finset.range k := Finset.mem_range.mpr (by omega)
  calc (∑ i ∈ Finset.range k, if n % k = (i : ℤ) then f n else 0)
      = ∑ i ∈ Finset.range k, if i = (n % k).toNat then f n else 0 := by
        refine Finset.sum_congr rfl fun i _ => ?_
        by_cases hcase : n % k = (i : ℤ)
        · rw [if_pos hcase, if_pos (by omega)]
        · rw [if_neg hcase, if_neg (by omega)]
    _ = f n := by
        rw [Finset.sum_ite_eq' (Finset.range k) ((n % k).toNat) fun _ => f n, if_pos hmem]

/-- The weight extension is a weight family. -/
lemma isWeightFamily_weightExtend (hk : 0 < k) (v : Fin k → K) :
    t.IsWeightFamily k A (weightExtend (t := t) hk A v) :=
  ⟨fun u => summable_weightExtend (t := t) (A := A) hk v u, weightExtend_step hk v⟩

end Extend

/-! ### The weight space as a finite-dimensional submodule -/

section Space

variable {k : ℕ} {A : Kˣ}

/-- The space of weight-`k` theta families as a submodule of `ℤ → K`. -/
def weightSpace (k : ℕ) (A : Kˣ) : Submodule K (ℤ → K) where
  carrier := {c | t.IsWeightFamily k A c}
  add_mem' hc hd := hc.add hd
  zero_mem' := IsWeightFamily.zero
  smul_mem' a _ hc := hc.smul a

variable {t}

omit [CompleteSpace K] [IsUltrametricDist K] in
@[simp] lemma mem_weightSpace {c : ℤ → K} :
    c ∈ t.weightSpace k A ↔ t.IsWeightFamily k A c := Iff.rfl

/-- **The dimension count**: initial coefficients give a linear equivalence of the
weight-`k` space with `Fin k → K`. -/
def weightEquiv (hk : 0 < k) : t.weightSpace k A ≃ₗ[K] (Fin k → K) where
  toFun c := fun i => (c : ℤ → K) (i : ℕ)
  map_add' c d := by funext i; simp
  map_smul' a c := by funext i; simp
  invFun v := ⟨weightExtend (t := t) hk A v, isWeightFamily_weightExtend hk v⟩
  left_inv c := by
    apply Subtype.ext
    exact IsWeightFamily.ext_initial hk
      (isWeightFamily_weightExtend (t := t) (A := A) hk fun j => (c : ℤ → K) (j : ℕ)) c.2
      fun i hi => weightExtend_initial (t := t) (A := A) hk
        (fun j => (c : ℤ → K) (j : ℕ)) i hi
  right_inv v := by
    funext i
    have h := weightExtend_initial (t := t) (A := A) hk v i i.2
    simpa using h

/-- The weight-`k` space is `k`-dimensional. -/
lemma finrank_weightSpace (hk : 0 < k) :
    Module.finrank K (t.weightSpace k A) = k := by
  rw [LinearEquiv.finrank_eq (weightEquiv (t := t) (A := A) hk)]
  simp [Module.finrank_fintype_fun_eq_card]

lemma finiteDimensional_weightSpace (hk : 0 < k) :
    FiniteDimensional K (t.weightSpace k A) :=
  Module.Finite.equiv (weightEquiv (t := t) (A := A) hk).symm

end Space

/-! ### Theta blocks, evaluation, and division -/

section Block

variable {k : ℕ} {A : Kˣ}

/-- The **theta block** at `e : Kˣ`: the coefficient family of `u ↦ θ(e·u)`, a weight-one
family with multiplier `(q·e)⁻¹`. Its zero class is the class of `-e⁻¹`. -/
def thetaBlock (e : Kˣ) : ℤ → K := fun n => (t.q : K) ^ thetaExp n * (e : K) ^ n

variable {t}

omit [CompleteSpace K] [IsUltrametricDist K] in
@[simp] lemma thetaBlock_apply (e : Kˣ) (n : ℤ) :
    t.thetaBlock e n = (t.q : K) ^ thetaExp n * (e : K) ^ n := rfl

lemma summable_thetaBlock (e u : Kˣ) :
    Summable fun n : ℤ => t.thetaBlock e n * (u : K) ^ n := by
  refine (t.thetaTerm_summable (e * u)).congr fun n => ?_
  rw [thetaTerm, thetaBlock_apply, Units.val_mul, mul_zpow]
  ring

omit [CompleteSpace K] [IsUltrametricDist K] in
/-- The theta block's series is `θ(e·u)`. -/
lemma tsum_thetaBlock (e u : Kˣ) :
    (∑' n : ℤ, t.thetaBlock e n * (u : K) ^ n) = t.theta (e * u) := by
  rw [theta_apply]
  refine tsum_congr fun n => ?_
  rw [thetaBlock_apply, Units.val_mul, mul_zpow]
  ring

/-- The theta block is a weight-one family with multiplier `(q·e)⁻¹`. -/
lemma isWeightFamily_thetaBlock (e : Kˣ) :
    t.IsWeightFamily 1 (t.q * e)⁻¹ (t.thetaBlock e) := by
  have hq0 : (t.q : K) ≠ 0 := t.q.ne_zero
  have he0 : (e : K) ≠ 0 := Units.ne_zero e
  refine ⟨summable_thetaBlock e, fun n => ?_⟩
  have hth : thetaExp (n + 1) = thetaExp n + (n + 1) := by
    have h1 := two_mul_thetaExp (n + 1)
    have h2 := two_mul_thetaExp n
    have h3 : (n + 1) * (n + 1 + 1) = n * (n + 1) + 2 * (n + 1) := by ring
    linarith
  rw [Units.val_inv_eq_inv_val, Units.val_mul]
  simp only [thetaBlock_apply, Nat.cast_one]
  rw [hth, zpow_add₀ hq0, zpow_add₀ he0, zpow_add₀ hq0, zpow_one, zpow_one]
  field_simp

/-- Pointwise products of summable families are summable (nonarchimedean). -/
private lemma summable_mul_pointwise' {f g : ℤ → K} (hf : Summable f) (hg : Summable g) :
    Summable fun m : ℤ => f m * g m := by
  have h := hf.tendsto_cofinite_zero.mul hg.tendsto_cofinite_zero
  rw [mul_zero] at h
  exact NonarchimedeanAddGroup.summable_of_tendsto_cofinite_zero h

omit [CompleteSpace K] [IsUltrametricDist K] in
/-- A weight family is summable as a bare coefficient family. -/
lemma IsWeightFamily.summable_coeff {c : ℤ → K} (hc : t.IsWeightFamily k A c) :
    Summable c := by
  have h := hc.summable 1
  refine h.congr fun n => ?_
  simp

/-- **Evaluation at a point** as a linear functional on the weight space. -/
def evalAt (x : Kˣ) (k : ℕ) (A : Kˣ) : t.weightSpace k A →ₗ[K] K where
  toFun c := ∑' n : ℤ, (c : ℤ → K) n * (x : K) ^ n
  map_add' c d := by
    have hc := c.2.summable x
    have hd := d.2.summable x
    rw [← hc.tsum_add hd]
    refine tsum_congr fun n => ?_
    simp [add_mul]
  map_smul' a c := by
    simp only [RingHom.id_apply, smul_eq_mul]
    rw [← tsum_mul_left]
    refine tsum_congr fun n => ?_
    simp [mul_assoc]

set_option linter.unusedSectionVars false in
@[simp] lemma evalAt_apply (x : Kˣ) (c : t.weightSpace k A) :
    evalAt x k A c = ∑' n : ℤ, (c : ℤ → K) n * (x : K) ^ n := rfl

/-- **Multiplication by a theta block** as a linear map raising the weight by one. -/
def convBlock (e : Kˣ) (k : ℕ) (A : Kˣ) :
    t.weightSpace k A →ₗ[K] t.weightSpace (1 + k) ((t.q * e)⁻¹ * A) where
  toFun c := ⟨fun n => ∑' m : ℤ, t.thetaBlock e (n - m) * (c : ℤ → K) m,
    (isWeightFamily_thetaBlock e).conv c.2⟩
  map_add' c d := by
    apply Subtype.ext
    funext n
    have hb : Summable fun m : ℤ => t.thetaBlock e (n - m) :=
      (isWeightFamily_thetaBlock (t := t) e).summable_coeff.comp_injective
        fun a b hab => by omega
    have hc := summable_mul_pointwise' hb c.2.summable_coeff
    have hd := summable_mul_pointwise' hb d.2.summable_coeff
    simp only [Submodule.coe_add, Pi.add_apply]
    rw [← hc.tsum_add hd]
    refine tsum_congr fun m => ?_
    simp [mul_add]
  map_smul' a c := by
    apply Subtype.ext
    funext n
    simp only [RingHom.id_apply, SetLike.val_smul, Pi.smul_apply, smul_eq_mul]
    rw [← tsum_mul_left]
    refine tsum_congr fun m => ?_
    ring

@[simp] lemma convBlock_apply (e : Kˣ) (c : t.weightSpace k A) (n : ℤ) :
    (convBlock (t := t) e k A c : ℤ → K) n
      = ∑' m : ℤ, t.thetaBlock e (n - m) * (c : ℤ → K) m := rfl

/-- The series of a block convolution is `θ(e·u)` times the series. -/
lemma evalAt_convBlock (e : Kˣ) (c : t.weightSpace k A) (u : Kˣ) :
    evalAt u (1 + k) ((t.q * e)⁻¹ * A) (convBlock (t := t) e k A c)
      = t.theta (e * u) * evalAt u k A c := by
  have hsc : Summable fun n : ℤ => (c : ℤ → K) n * (u : K) ^ n := c.2.summable u
  have h : HasSum
      (fun ℓ : ℤ => (∑' m : ℤ, t.thetaBlock e (ℓ - m) * (c : ℤ → K) m) * (u : K) ^ ℓ)
      ((∑' n : ℤ, t.thetaBlock e n * (u : K) ^ n)
        * ∑' n : ℤ, (c : ℤ → K) n * (u : K) ^ n) :=
    hasSum_laurentConvolution u (summable_thetaBlock (t := t) e u).hasSum hsc.hasSum
  rw [tsum_thetaBlock e u] at h
  exact h.tsum_eq

/-- **Injectivity of block multiplication**: convolving with a theta block kills no
weight family — a nonzero family's series has finitely many unit-sphere zeros, while a
vanishing block product forces vanishing off a single unit-sphere point. -/
theorem convBlock_injective (e : Kˣ) (k : ℕ) (A : Kˣ) :
    Function.Injective (convBlock (t := t) e k A) := by
  rw [injective_iff_map_eq_zero]
  intro c hc0
  by_contra hne
  have hcfam : (c : ℤ → K) ≠ 0 := fun h => hne (Subtype.ext h)
  have hfin := TateCurvesTheta.StrassmannSphere.finite_zeros
    (c := (c : ℤ → K)) c.2.summable_coeff hcfam
  -- every unit-sphere point off the block's zero class is a zero of the series
  have hzero : ∀ u : Kˣ, t.theta (e * u) ≠ 0 → (∑' n : ℤ, (c : ℤ → K) n * (u : K) ^ n) = 0 := by
    intro u hθ
    have hval := evalAt_convBlock (t := t) e c u
    rw [hc0, map_zero] at hval
    rcases mul_eq_zero.mp hval.symm with h | h
    · exact absurd h hθ
    · simpa using h
  -- at most one witness `1 + q^{j+1}` lies on the zero class
  have hbad : ∀ j₁ j₂ : ℕ, t.theta (e * t.sphereWitness j₁) = 0 →
      t.theta (e * t.sphereWitness j₂) = 0 → j₁ = j₂ := by
    intro j₁ j₂ h₁ h₂
    obtain ⟨k₁, hk₁⟩ := (t.theta_eq_zero_iff _).mp h₁
    obtain ⟨k₂, hk₂⟩ := (t.theta_eq_zero_iff _).mp h₂
    have hn₁ : ‖((e * t.sphereWitness j₁ : Kˣ) : K)‖ = ‖(e : K)‖ := by
      rw [Units.val_mul, norm_mul, t.sphereWitness_val, t.norm_one_add_qpow, mul_one]
    have hn₂ : ‖((e * t.sphereWitness j₂ : Kˣ) : K)‖ = ‖(e : K)‖ := by
      rw [Units.val_mul, norm_mul, t.sphereWitness_val, t.norm_one_add_qpow, mul_one]
    have hkk : k₁ = k₂ := by
      have h₁' := congrArg norm hk₁
      have h₂' := congrArg norm hk₂
      rw [hn₁, norm_neg, norm_zpow] at h₁'
      rw [hn₂, norm_neg, norm_zpow] at h₂'
      have hq1 : ‖(t.q : K)‖ < 1 := t.norm_lt_one
      have hq0 : 0 < ‖(t.q : K)‖ := t.norm_q_pos
      by_contra hne'
      rcases lt_or_gt_of_ne hne' with h | h
      · have := zpow_lt_zpow_right_of_lt_one₀ hq0 hq1 h
        rw [← h₁', ← h₂'] at this
        exact lt_irrefl _ this
      · have := zpow_lt_zpow_right_of_lt_one₀ hq0 hq1 h
        rw [← h₁', ← h₂'] at this
        exact lt_irrefl _ this
    rw [hkk] at hk₁
    have : ((t.sphereWitness j₁ : Kˣ) : K) = ((t.sphereWitness j₂ : Kˣ) : K) := by
      have := hk₁.trans hk₂.symm
      rw [Units.val_mul, Units.val_mul] at this
      exact mul_left_cancel₀ (Units.ne_zero e) this
    exact t.sphereWitness_injective (Units.ext this)
  -- so infinitely many witnesses are zeros: contradiction with Strassmann finiteness
  have hmem : ∀ j : ℕ, t.theta (e * t.sphereWitness j) ≠ 0 →
      ((t.sphereWitness j : Kˣ) : K) ∈
        {v : K | ‖v‖ = 1 ∧ (∑' n : ℤ, (c : ℤ → K) n * v ^ n) = 0} := by
    intro j hj
    refine ⟨by rw [t.sphereWitness_val]; exact t.norm_one_add_qpow j, ?_⟩
    exact hzero (t.sphereWitness j) hj
  classical
  by_cases hex : ∃ j₀ : ℕ, t.theta (e * t.sphereWitness j₀) = 0
  · obtain ⟨j₀, hj₀⟩ := hex
    have hinj : Function.Injective fun j : ℕ => ((t.sphereWitness (j + j₀ + 1) : Kˣ) : K) :=
      fun a b hab => by
        have := t.sphereWitness_injective (Units.ext hab)
        omega
    refine Set.infinite_of_injective_forall_mem hinj (fun j => hmem _ fun hz => ?_) hfin
    have := hbad _ _ hz hj₀
    omega
  · rw [not_exists] at hex
    have hinj : Function.Injective fun j : ℕ => ((t.sphereWitness j : Kˣ) : K) :=
      fun a b hab => t.sphereWitness_injective (Units.ext hab)
    exact Set.infinite_of_injective_forall_mem hinj (fun j => hmem j (hex j)) hfin

/-- **Division by a theta block.** If a weight-`(1+k)` family `F` vanishes at one point
`x₀` of the block's zero class, and the space contains a witness `g` NOT vanishing at
`x₀`, then `F` is a block convolution: `F = θ_e ⋆ c` for some weight-`k` family `c`.
This is the nonarchimedean Abel step, executed by pure dimension counting. -/
theorem exists_convBlock_eq (hk : 0 < k) (e : Kˣ) {x₀ : Kˣ}
    (hx₀ : t.theta (e * x₀) = 0)
    (g : t.weightSpace (1 + k) ((t.q * e)⁻¹ * A))
    (hg : evalAt x₀ (1 + k) ((t.q * e)⁻¹ * A) g ≠ 0)
    (F : t.weightSpace (1 + k) ((t.q * e)⁻¹ * A))
    (hF : evalAt x₀ (1 + k) ((t.q * e)⁻¹ * A) F = 0) :
    ∃ c : t.weightSpace k A, convBlock (t := t) e k A c = F := by
  haveI : FiniteDimensional K (t.weightSpace (1 + k) ((t.q * e)⁻¹ * A)) :=
    finiteDimensional_weightSpace (by omega)
  haveI : FiniteDimensional K (t.weightSpace k A) := finiteDimensional_weightSpace hk
  set ev := evalAt (t := t) x₀ (1 + k) ((t.q * e)⁻¹ * A) with hev
  set Φ := convBlock (t := t) e k A with hΦ
  -- the image lands in the kernel of the evaluation
  have himle : LinearMap.range Φ ≤ LinearMap.ker ev := by
    rintro _ ⟨c, rfl⟩
    rw [LinearMap.mem_ker, hev, hΦ, evalAt_convBlock, hx₀, zero_mul]
  -- dimensions: range has k, kernel has k
  have hrange : Module.finrank K (LinearMap.range Φ) = k := by
    rw [LinearMap.finrank_range_of_inj (convBlock_injective e k A)]
    exact finrank_weightSpace hk
  have hker : Module.finrank K (LinearMap.ker ev) = k := by
    have hspace : Module.finrank K (t.weightSpace (1 + k) ((t.q * e)⁻¹ * A)) = 1 + k :=
      finrank_weightSpace (by omega)
    have hrn := LinearMap.finrank_range_add_finrank_ker ev
    have hr1 : Module.finrank K (LinearMap.range ev) = 1 := by
      have hle : Module.finrank K (LinearMap.range ev) ≤ 1 := by
        have h := Submodule.finrank_le (LinearMap.range ev)
        simpa using h
      have hne : LinearMap.range ev ≠ ⊥ := by
        intro h0
        have h1 : ev = 0 := LinearMap.range_eq_bot.mp h0
        rw [h1] at hg
        simp at hg
      have hge : 1 ≤ Module.finrank K (LinearMap.range ev) := by
        by_contra hlt
        have h0 : Module.finrank K (LinearMap.range ev) = 0 := by omega
        exact hne (Submodule.finrank_eq_zero.mp h0)
      omega
    rw [hspace, hr1] at hrn
    omega
  have heq : LinearMap.range Φ = LinearMap.ker ev :=
    Submodule.eq_of_le_of_finrank_le himle (by rw [hker, hrange])
  have hFmem : F ∈ LinearMap.range Φ := by
    rw [heq, LinearMap.mem_ker]
    exact hF
  exact hFmem

/-- Family-level form of the division theorem, with the ambient multiplier given by a
propositional equation — convenient at application sites. -/
theorem exists_convBlock_eq' (hk : 0 < k) (e : Kˣ) {M : Kˣ} (hM : (t.q * e)⁻¹ * A = M)
    {x₀ : Kˣ} (hx₀ : t.theta (e * x₀) = 0)
    (g : t.weightSpace (1 + k) M) (hg : evalAt x₀ (1 + k) M g ≠ 0)
    (F : t.weightSpace (1 + k) M) (hF : evalAt x₀ (1 + k) M F = 0) :
    ∃ c : t.weightSpace k A,
      ∀ n : ℤ, (∑' m : ℤ, t.thetaBlock e (n - m) * (c : ℤ → K) m) = (F : ℤ → K) n := by
  subst hM
  obtain ⟨c, hc⟩ := exists_convBlock_eq hk e hx₀ g hg F hF
  exact ⟨c, fun n => by rw [← hc]; rfl⟩

/-- **Weight-one classification**: a weight-one family is a scalar multiple of the theta
block with the matching multiplier. -/
theorem w1_eq_smul_thetaBlock {A : Kˣ} {c : ℤ → K}
    (hc : t.IsWeightFamily 1 A c) :
    c = c 0 • t.thetaBlock ((t.q * A)⁻¹) := by
  have hblock := isWeightFamily_thetaBlock (t := t) ((t.q * A)⁻¹)
  have hmul : (t.q * (t.q * A)⁻¹)⁻¹ = A := by
    rw [mul_inv, inv_inv, ← mul_assoc, inv_mul_cancel, one_mul]
  rw [hmul] at hblock
  refine IsWeightFamily.ext_initial Nat.one_pos hc (hblock.smul (c 0)) fun i hi => ?_
  interval_cases i
  simp [thetaBlock_apply, thetaExp]

/-- **Uniqueness off one orbit**: globally summable families whose series agree at every
point off the `qᶻ`-orbit are equal — Strassmann finiteness against the infinitely many
norm-one witnesses. -/
theorem laurent_ext_off_orbit {a b : ℤ → K}
    (ha : ∀ u : Kˣ, Summable fun n : ℤ => a n * (u : K) ^ n)
    (hb : ∀ u : Kˣ, Summable fun n : ℤ => b n * (u : K) ^ n)
    (h : ∀ u : Kˣ, (∀ n : ℤ, (t.q : K) ^ n * (u : K) ≠ 1) →
      (∑' n : ℤ, a n * (u : K) ^ n) = ∑' n : ℤ, b n * (u : K) ^ n) : a = b := by
  by_contra hne
  have hd0 : (fun n : ℤ => a n - b n) ≠ 0 := by
    intro h0
    exact hne (funext fun n => sub_eq_zero.mp (congrFun h0 n))
  have hdsum : Summable fun n : ℤ => a n - b n := by
    refine ((ha 1).sub (hb 1)).congr fun n => ?_
    simp
  have hfin := TateCurvesTheta.StrassmannSphere.finite_zeros hdsum hd0
  have hmem : ∀ j : ℕ, ((t.sphereWitness j : Kˣ) : K) ∈
      {v : K | ‖v‖ = 1 ∧ (∑' n : ℤ, (a n - b n) * v ^ n) = 0} := by
    intro j
    have hnorm : ‖((t.sphereWitness j : Kˣ) : K)‖ = 1 := by
      rw [t.sphereWitness_val]
      exact t.norm_one_add_qpow j
    refine ⟨hnorm, ?_⟩
    have hoff : ∀ n : ℤ, (t.q : K) ^ n * ((t.sphereWitness j : Kˣ) : K) ≠ 1 := by
      intro n hcontra
      have h1 := congrArg norm hcontra
      rw [norm_mul, norm_zpow, hnorm, mul_one, norm_one] at h1
      have hq1 : ‖(t.q : K)‖ < 1 := t.norm_lt_one
      have hq0 : 0 < ‖(t.q : K)‖ := t.norm_q_pos
      have hn0 : n = 0 := by
        by_contra hn
        rcases lt_or_gt_of_ne hn with hlt | hgt
        · have hmono := zpow_lt_zpow_right_of_lt_one₀ hq0 hq1 hlt
          rw [zpow_zero, h1] at hmono
          exact lt_irrefl _ hmono
        · have hmono := zpow_lt_zpow_right_of_lt_one₀ hq0 hq1 hgt
          rw [zpow_zero, h1] at hmono
          exact lt_irrefl _ hmono
      rw [hn0, zpow_zero, one_mul, t.sphereWitness_val] at hcontra
      have hz : (t.q : K) ^ (j + 1) = 0 := by linear_combination hcontra
      exact pow_ne_zero (j + 1) t.q.ne_zero hz
    have heq := h (t.sphereWitness j) hoff
    calc (∑' n : ℤ, (a n - b n) * ((t.sphereWitness j : Kˣ) : K) ^ n)
        = ∑' n : ℤ, (a n * ((t.sphereWitness j : Kˣ) : K) ^ n
            - b n * ((t.sphereWitness j : Kˣ) : K) ^ n) := by
          refine tsum_congr fun n => ?_
          ring
      _ = (∑' n : ℤ, a n * ((t.sphereWitness j : Kˣ) : K) ^ n)
            - ∑' n : ℤ, b n * ((t.sphereWitness j : Kˣ) : K) ^ n :=
          Summable.tsum_sub (ha _) (hb _)
      _ = 0 := by rw [heq, sub_self]
  have hinj : Function.Injective fun j : ℕ => ((t.sphereWitness j : Kˣ) : K) :=
    fun x y hxy => t.sphereWitness_injective (Units.ext hxy)
  exact Set.infinite_of_injective_forall_mem hinj hmem hfin

/-- Weight-family membership from the value functional equation off the orbit. -/
theorem isWeightFamily_of_tsum_q_smul_off_orbit {k : ℕ} {A : Kˣ} {c : ℤ → K}
    (hsum : ∀ u : Kˣ, Summable fun n : ℤ => c n * (u : K) ^ n)
    (h : ∀ u : Kˣ, (∀ n : ℤ, (t.q : K) ^ n * (u : K) ≠ 1) →
      (∑' n : ℤ, c n * ((t.q : K) * (u : K)) ^ n)
        = (A : K) * (u : K) ^ (-(k : ℤ)) * ∑' n : ℤ, c n * (u : K) ^ n) :
    t.IsWeightFamily k A c := by
  refine ⟨hsum, fun n => ?_⟩
  have hsumA : ∀ u : Kˣ, Summable fun n : ℤ => ((t.q : K) ^ n * c n) * (u : K) ^ n := by
    intro u
    refine (hsum (t.q * u)).congr fun n => ?_
    rw [Units.val_mul, mul_zpow]
    ring
  have hsumB : ∀ u : Kˣ, Summable fun n : ℤ => ((A : K) * c (n + k)) * (u : K) ^ n := by
    intro u
    have h1 : Summable fun n : ℤ => c (n + k) * (u : K) ^ (n + k) :=
      (hsum u).comp_injective (add_left_injective (k : ℤ))
    have h2 := h1.mul_right ((u : K) ^ (-(k : ℤ)))
    have h3 : Summable fun n : ℤ => c (n + k) * (u : K) ^ n := by
      refine h2.congr fun n => ?_
      rw [mul_assoc, ← zpow_add₀ (Units.ne_zero u)]
      congr 2
      omega
    refine (h3.mul_left (A : K)).congr fun n => ?_
    ring
  have key : (fun n : ℤ => (t.q : K) ^ n * c n) = fun n : ℤ => (A : K) * c (n + k) := by
    refine laurent_ext_off_orbit (t := t) hsumA hsumB fun u hu => ?_
    have hL : (∑' n : ℤ, ((t.q : K) ^ n * c n) * (u : K) ^ n)
        = ∑' n : ℤ, c n * ((t.q : K) * (u : K)) ^ n := by
      refine tsum_congr fun n => ?_
      rw [mul_zpow]
      ring
    have hR : (∑' n : ℤ, ((A : K) * c (n + k)) * (u : K) ^ n)
        = (A : K) * (u : K) ^ (-(k : ℤ)) * ∑' n : ℤ, c n * (u : K) ^ n := by
      have h2 : (∑' n : ℤ, c (n + k) * (u : K) ^ (n + k))
          = ∑' n : ℤ, c n * (u : K) ^ n := by
        rw [← (Equiv.addRight (k : ℤ)).tsum_eq fun n => c n * (u : K) ^ n]
        exact tsum_congr fun n => rfl
      rw [← h2, ← tsum_mul_left]
      refine tsum_congr fun n => ?_
      rw [zpow_add₀ (Units.ne_zero u), zpow_neg]
      field_simp
    rw [hL, hR, h u hu]
  have hkey := congrFun key n
  linear_combination -hkey

omit [CompleteSpace K] in
/-- **Avoiding finitely many orbit classes**: some unit lies outside every `qᶻy`-class for
`y` in a given finite set — infinitely many witnesses, finitely many classes. -/
theorem exists_unit_avoiding (S : Finset Kˣ) :
    ∃ s : Kˣ, ∀ y ∈ S, ∀ n : ℤ, (s : K) ≠ (t.q : K) ^ n * (y : K) := by
  by_contra hcontra
  rw [not_exists] at hcontra
  have hchoice : ∀ j : ℕ, ∃ y ∈ S, ∃ n : ℤ,
      ((t.sphereWitness j : Kˣ) : K) = (t.q : K) ^ n * (y : K) := by
    intro j
    by_contra hj
    exact hcontra (t.sphereWitness j) fun y hy n hn => hj ⟨y, hy, n, hn⟩
  choose f hfS g hfg using hchoice
  have hSfin : Set.Finite (Set.range f) := (S.finite_toSet.subset (by
    rintro _ ⟨j, rfl⟩
    exact hfS j))
  have hinjW : Function.Injective t.sphereWitness := t.sphereWitness_injective
  -- two witnesses on the same class coincide: contradiction with infinitude
  have hkey : ∀ j₁ j₂ : ℕ, f j₁ = f j₂ → j₁ = j₂ := by
    intro j₁ j₂ hf12
    have h₁ := hfg j₁
    have h₂ := hfg j₂
    rw [hf12] at h₁
    have hnorm₁ : ‖((t.sphereWitness j₁ : Kˣ) : K)‖ = 1 := by
      rw [t.sphereWitness_val]; exact t.norm_one_add_qpow j₁
    have hnorm₂ : ‖((t.sphereWitness j₂ : Kˣ) : K)‖ = 1 := by
      rw [t.sphereWitness_val]; exact t.norm_one_add_qpow j₂
    have hq1 : ‖(t.q : K)‖ < 1 := t.norm_lt_one
    have hq0 : 0 < ‖(t.q : K)‖ := t.norm_q_pos
    have hnn : g j₁ = g j₂ := by
      have e₁ := congrArg norm h₁
      have e₂ := congrArg norm h₂
      rw [norm_mul, norm_zpow, hnorm₁] at e₁
      rw [norm_mul, norm_zpow, hnorm₂] at e₂
      have hy0 : 0 < ‖((f j₂ : Kˣ) : K)‖ := norm_pos_iff.mpr (Units.ne_zero _)
      have heq : ‖(t.q : K)‖ ^ g j₁ = ‖(t.q : K)‖ ^ g j₂ :=
        mul_right_cancel₀ hy0.ne' (e₁.symm.trans e₂)
      by_contra hne'
      rcases lt_or_gt_of_ne hne' with hlt | hgt
      · have := zpow_lt_zpow_right_of_lt_one₀ hq0 hq1 hlt
        rw [heq] at this
        exact lt_irrefl _ this
      · have := zpow_lt_zpow_right_of_lt_one₀ hq0 hq1 hgt
        rw [heq] at this
        exact lt_irrefl _ this
    rw [hnn] at h₁
    have : ((t.sphereWitness j₁ : Kˣ) : K) = ((t.sphereWitness j₂ : Kˣ) : K) :=
      h₁.trans h₂.symm
    exact hinjW (Units.ext this)
  have hinjf : Function.Injective f := fun a b hab => hkey a b hab
  exact Set.infinite_range_of_injective hinjf hSfin

end Block

end TateParameter

end TateCurvesTheta
